### PR TITLE
Add -f/--force option, currently undocumented

### PR DESCRIPTION
**Pull request by mmrwoods**
Experimental, adds a force option to just do whatever it takes to
rotate, trashing unknown keys, ignoring conflicting profiles etc.

### CODE REVIEW

**Comment by mmrwoods** [comment]
Note: branch based off `feature/improve-error-handling`

**Comment by rhyeal** [comment]
I see the 3 PRs you've got pending. On travel this week, but I'll try to review and get them merged in on Friday.

**Comment by mmrwoods** [comment]
No problem, thanks.

I have another update at mmrwoods/aws-rotate-iam-keys to allow installation of HEAD and devel versions from the forked repo. This is quite a hack, but it has worked nicely for us. I'll open a PR for you to take a look and see what you think.

**Review by rhyeal — APPROVED** [review]
I like the addition of the `--force` option. This will come in handy when there are two computers a dev is using and you need to ensure your other machine is taken out of the loop, while traveling for instance!

**Pull request merged**
