### PR TITLE
Update aws-rotate-iam-keys.rb

### LINKED ISSUE #17: MacOS Homebrew ChecksumMismatchError
Hello!

I'm following the instructions to install this on my Mac (10.14.5), but Homebrew gives me the following error:
```SHELL
wks-000671:~ jplachance$ brew search aws-rotate-iam-keys
==> Formulae
rhyeal/aws-rotate-iam-keys/aws-rotate-iam-keys
wks-000671:~ jplachance$ brew install rhyeal/aws-rotate-iam-keys/aws-rotate-iam-keys
==> Installing aws-rotate-iam-keys from rhyeal/aws-rotate-iam-keys
==> Downloading https://github.com/rhyeal/aws-rotate-iam-keys/archive/v0.9.2.tar.gz
Already downloaded: /Users/jplachance/Library/Caches/Homebrew/downloads/ac8e0f9303ae07d8bec762733bb357796a5236df656317a779653bcaec640429--aws-rotate-iam-keys-0.9.2.tar.gz
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 997230eb7c75282a951ee4e83310f2830e453a1e121cfe84cfd4733a69b6d3b9
  Actual: 9101bff2a889e5c883fda99b12588dd50bee9d42faf77f6d6e5d94ab35abb9e1
 Archive: /Users/jplachance/Library/Caches/Homebrew/downloads/ac8e0f9303ae07d8bec762733bb357796a5236df656317a779653bcaec640429--aws-rotate-iam-keys-0.9.2.tar.gz
To retry an incomplete download, remove the file above.
```

How can I get rid of that error without the `--force` flag? 🙂 

Thanks for the help!

### PR DESCRIPTION
**Pull request by adamo57**
Fixes #17

### CODE REVIEW

**Review by JPLachance — APPROVED** [review]
Thanks! 🎉

**Comment by sc250024** [comment]
Is it possible to get this merged? Would like to install the `aws-rotate-iam-keys` installed since it's an awesome tool!

**Comment by sc250024** [comment]
Who can merge this? It looks like it was already approved.

**Comment by rhyeal** [comment]
That was me messing up the hash. Sorry guys!

**Pull request merged**
